# Generated by Django 4.0.2 on 2022-02-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Digite o título da notícia')),
                ('legenda', models.CharField(max_length=100, verbose_name='Digite a legenda da notícia')),
                ('texto', models.TextField(verbose_name='Digite o texto da notícia')),
            ],
        ),
    ]
