# Generated by Django 4.0.2 on 2022-02-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_noticias_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='imagem',
            field=models.ImageField(default='upload/slide_padrao.png', upload_to='uploads/', verbose_name='Escolha a imagem'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Digite o título da notícia'),
        ),
    ]
