# Generated by Django 4.0.2 on 2022-02-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_noticias_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagem',
            field=models.ImageField(default='static/img/slide_padrao.png', upload_to='static/img/', verbose_name='Escolha a imagem'),
        ),
    ]
