# Generated by Django 4.0.2 on 2022-02-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_noticias_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Digite o título foto')),
                ('imagem', models.ImageField(default='/foto_padrao.png', upload_to='uploads', verbose_name='Escolha a imagem')),
                ('legenda', models.CharField(max_length=100, verbose_name='Digite a legenda da foto')),
            ],
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagem',
            field=models.ImageField(default='/slide_padrao.png', upload_to='uploads', verbose_name='Escolha a imagem'),
        ),
    ]
