# Generated by Django 4.0.2 on 2022-02-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_fotos_alter_noticias_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='legenda',
            field=models.CharField(max_length=100, verbose_name='Digite a legenda da fotopa'),
        ),
    ]
