# Generated by Django 4.0.2 on 2022-02-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_fotos_legenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='imagem',
            field=models.ImageField(default='/foto_padrao.png', upload_to='uploads', verbose_name='Escolha a imagem:'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='legenda',
            field=models.CharField(max_length=100, verbose_name='Digite a legenda da fotopa:'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Digite o título foto:'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagem',
            field=models.ImageField(default='/slide_padrao.png', upload_to='uploads', verbose_name='Escolha a imagem:'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='legenda',
            field=models.CharField(max_length=100, verbose_name='Digite a legenda da notícia:'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='texto',
            field=models.TextField(verbose_name='Digite o texto da notícia:'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Digite o título da notícia:'),
        ),
    ]
