# Generated by Django 4.0.2 on 2022-02-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_fotos_imagem_alter_fotos_legenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagem',
            field=models.ImageField(default='/slide_padrao.png', upload_to='fotos', verbose_name='Escolha a imagem:'),
        ),
    ]
