# Generated by Django 4.0.2 on 2022-02-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_alter_fotos_imagem_alter_noticias_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('assunto', models.CharField(max_length=100, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
            ],
        ),
        migrations.AlterField(
            model_name='fotos',
            name='legenda',
            field=models.CharField(max_length=100, verbose_name='Digite a legenda da foto:'),
        ),
    ]
