# Generated by Django 4.0.2 on 2022-02-17 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_contato_alter_fotos_legenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data',
            field=models.DateField(default=datetime.date(2022, 2, 17)),
        ),
        migrations.AlterField(
            model_name='contato',
            name='assunto',
            field=models.CharField(max_length=100, verbose_name='Assunto:'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail:'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(verbose_name='Mensagem:'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome:'),
        ),
    ]
