# Generated by Django 4.0.2 on 2022-02-17 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_contato_data_alter_contato_assunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 19, 14, 53, 318642, tzinfo=utc)),
        ),
    ]
