# Generated by Django 4.0.2 on 2022-02-18 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_alter_contato_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
