# Generated by Django 4.0.2 on 2022-02-18 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_contato_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='noticias',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='imagem',
            field=models.ImageField(default='fotos/foto_padrao.png', upload_to='fotos', verbose_name='Imagem:'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='legenda',
            field=models.CharField(max_length=100, verbose_name='Legenda:'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título:'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagem',
            field=models.ImageField(default='slides/slide_padrao.png', upload_to='slides', verbose_name='Imagem:'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='legenda',
            field=models.CharField(max_length=100, verbose_name='Legenda:'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='texto',
            field=models.TextField(verbose_name='Texto:'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título:'),
        ),
    ]
