# Generated by Django 4.0.2 on 2022-02-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_fotos_data_noticias_data_alter_fotos_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='categoria',
            field=models.CharField(choices=[('1', 'FUND_I'), ('2', 'FUND_II'), ('3', 'MEDIO')], default='FUND_I', max_length=20),
        ),
    ]
