# Generated by Django 4.0.2 on 2022-02-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_alter_fotos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='emailCap',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email CAP:'),
        ),
        migrations.AddField(
            model_name='contato',
            name='enderecoCap',
            field=models.TextField(default='Endereço: Av. Getúlio Vargas, 654 - Centro, 69900-150', verbose_name='Endereço CAP:'),
        ),
        migrations.AddField(
            model_name='contato',
            name='foneCap',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefone CAP:'),
        ),
    ]
