# Generated by Django 4.0.2 on 2022-03-01 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_contato_emailcap_contato_enderecocap_contato_fonecap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome:')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail:')),
                ('assunto', models.CharField(max_length=100, verbose_name='Assunto:')),
                ('mensagem', models.TextField(verbose_name='Mensagem:')),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ContatoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enderecoCap', models.TextField(default='Endereço: Av. Getúlio Vargas, 654 - Centro, Rio Branco - AC, 69900-150', verbose_name='Endereço CAP:')),
                ('emailCap', models.EmailField(default='cap@ufac.br', max_length=254, verbose_name='Email CAP:')),
                ('foneCap', models.CharField(default='(68) 99971-3692', max_length=20, verbose_name='Telefone CAP:')),
            ],
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
