# Generated by Django 4.0.2 on 2022-03-01 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_contatoform_contatopage_delete_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatopage',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contatopage',
            name='legenda',
            field=models.TextField(default='Aqui disponibilizamos várias formas para nos encontrar', verbose_name='Legenda:'),
        ),
        migrations.AddField(
            model_name='contatopage',
            name='titulo',
            field=models.CharField(default='Nossos Contatos', max_length=40, verbose_name='Título:'),
        ),
    ]
