# Generated by Django 4.0.2 on 2022-03-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_contatopage_data_contatopage_legenda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatopage',
            name='data',
        ),
        migrations.AlterField(
            model_name='contatopage',
            name='emailCap',
            field=models.EmailField(default='cap@ufac.br', max_length=254, null=True, verbose_name='Email CAP:'),
        ),
        migrations.AlterField(
            model_name='contatopage',
            name='enderecoCap',
            field=models.TextField(default='Endereço: Av. Getúlio Vargas, 654 - Centro, Rio Branco - AC, 69900-150', null=True, verbose_name='Endereço CAP:'),
        ),
        migrations.AlterField(
            model_name='contatopage',
            name='foneCap',
            field=models.CharField(default='(68) 99971-3692', max_length=20, null=True, verbose_name='Telefone CAP:'),
        ),
        migrations.AlterField(
            model_name='contatopage',
            name='legenda',
            field=models.TextField(default='Aqui disponibilizamos várias formas para nos encontrar', null=True, verbose_name='Legenda:'),
        ),
        migrations.AlterField(
            model_name='contatopage',
            name='titulo',
            field=models.CharField(default='Nossos Contatos', max_length=40, null=True, verbose_name='Título:'),
        ),
    ]
