# Generated by Django 4.0.2 on 2022-03-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_remove_contatopage_data_alter_contatopage_emailcap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatopage',
            name='emailCap',
            field=models.EmailField(blank=True, default='cap@ufac.br', max_length=254, null=True, verbose_name='Email CAP:'),
        ),
        migrations.AlterField(
            model_name='contatopage',
            name='enderecoCap',
            field=models.TextField(blank=True, default='Endereço: Av. Getúlio Vargas, 654 - Centro, Rio Branco - AC, 69900-150', null=True, verbose_name='Endereço CAP:'),
        ),
        migrations.AlterField(
            model_name='contatopage',
            name='foneCap',
            field=models.CharField(blank=True, default='(68) 99971-3692', max_length=20, null=True, verbose_name='Telefone CAP:'),
        ),
        migrations.AlterField(
            model_name='contatopage',
            name='legenda',
            field=models.TextField(blank=True, default='Aqui disponibilizamos várias formas para nos encontrar', null=True, verbose_name='Legenda:'),
        ),
        migrations.AlterField(
            model_name='contatopage',
            name='titulo',
            field=models.CharField(blank=True, default='Nossos Contatos', max_length=40, null=True, verbose_name='Título:'),
        ),
    ]
