# Generated by Django 4.0.2 on 2022-03-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_alter_contatopage_emailcap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatopage',
            name='titulo',
            field=models.CharField(default='Nossos Contatos', max_length=40, verbose_name='Título:'),
        ),
    ]
