# Generated by Django 4.0.2 on 2022-03-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_fotospage_alter_contatopage_legenda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotosPage',
        ),
        migrations.AddField(
            model_name='fotos',
            name='legendaPage',
            field=models.CharField(blank=True, default='Aqui são postadas as fotos dos nossos eventos e atividades escolares.', max_length=200, null=True, verbose_name='Legenda:'),
        ),
        migrations.AddField(
            model_name='fotos',
            name='tituloOne',
            field=models.CharField(default='Atividades Escolares e', max_length=40, verbose_name='Título I:'),
        ),
        migrations.AddField(
            model_name='fotos',
            name='tituloTwo',
            field=models.CharField(default='Eventos', max_length=40, verbose_name='Título II:'),
        ),
    ]
