# Generated by Django 4.0.2 on 2022-03-05 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0030_fotospage_remove_fotos_legendapage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='%d-%m-%Y'),
        ),
    ]
