# Generated by Django 4.0.2 on 2022-03-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0033_alter_contatopage_mapacap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatopage',
            name='legenda',
            field=models.CharField(blank=True, default='Aqui disponibilizamos várias formas para nos encontrar', max_length=200, null=True, verbose_name='Legenda:'),
        ),
        migrations.AlterField(
            model_name='fotospage',
            name='legenda',
            field=models.CharField(blank=True, default='Aqui são postadas as fotos dos nossos eventos e atividades escolares', max_length=200, null=True, verbose_name='Legenda:'),
        ),
    ]
