# Generated by Django 4.0.2 on 2022-03-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0037_remove_noticias_legenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='legenda',
            field=models.CharField(blank=True, default=2022, max_length=100, null=True, verbose_name='Legenda:'),
        ),
    ]
