# Generated by Django 4.0.2 on 2022-03-07 18:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0039_noticias_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missao', models.TextField(verbose_name='Missão:')),
                ('visao', models.TextField(verbose_name='Visão:')),
                ('valores', models.TextField(verbose_name='Valores:')),
            ],
        ),
        migrations.AlterField(
            model_name='noticias',
            name='texto',
            field=ckeditor.fields.RichTextField(verbose_name='Texto:'),
        ),
    ]
