# Generated by Django 4.0.2 on 2022-03-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0040_pilares_alter_noticias_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotospage',
            old_name='tituloOne',
            new_name='titulo_one',
        ),
        migrations.RenameField(
            model_name='fotospage',
            old_name='tituloTwo',
            new_name='titulo_two',
        ),
        migrations.RemoveField(
            model_name='pilares',
            name='missao',
        ),
        migrations.RemoveField(
            model_name='pilares',
            name='valores',
        ),
        migrations.RemoveField(
            model_name='pilares',
            name='visao',
        ),
        migrations.AddField(
            model_name='pilares',
            name='pilar_one',
            field=models.TextField(blank=True, null=True, verbose_name='Pilar I:'),
        ),
        migrations.AddField(
            model_name='pilares',
            name='pilar_three',
            field=models.TextField(blank=True, null=True, verbose_name='Pilar II:'),
        ),
        migrations.AddField(
            model_name='pilares',
            name='pilar_two',
            field=models.TextField(blank=True, null=True, verbose_name='Pilar II:'),
        ),
        migrations.AddField(
            model_name='pilares',
            name='titulo_one',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título I:'),
        ),
        migrations.AddField(
            model_name='pilares',
            name='titulo_three',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título I:'),
        ),
        migrations.AddField(
            model_name='pilares',
            name='titulo_two',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título I:'),
        ),
        migrations.AlterField(
            model_name='contatopage',
            name='mapaCap',
            field=models.TextField(default='https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15718.196648683606!2d-67.8106109!3d-9.9714163!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x589d3c359dec27ca!2zQ29sw6lnaW8gZGUgQXBsaWNhw6fDo28gZGEgVWZhYw!5e0!3m2!1spt-BR!2sbr!4v1644278509347!5m2!1spt-BR!2sbr', max_length=400, verbose_name='Link do Mapa: '),
        ),
    ]
