# Generated by Django 4.0.2 on 2022-03-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0043_gestaopage_sobrepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicosPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_one', models.CharField(default='Alguns dos nossos', max_length=100, verbose_name='Título I:')),
                ('titulo_two', models.CharField(default='Servicos', max_length=100, verbose_name='Título II:')),
                ('legenda', models.CharField(blank=True, default='Relação de alguns dos nossos serviços que você aluno(a) pode solicitar online.', max_length=200, null=True, verbose_name='Legenda:')),
            ],
        ),
        migrations.AlterField(
            model_name='fotospage',
            name='titulo_one',
            field=models.CharField(default='Atividades Escolares e', max_length=100, verbose_name='Título I:'),
        ),
        migrations.AlterField(
            model_name='fotospage',
            name='titulo_two',
            field=models.CharField(default='Eventos', max_length=100, verbose_name='Título II:'),
        ),
    ]
