# Generated by Django 4.0.2 on 2022-03-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0044_servicospage_alter_fotospage_titulo_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=100, verbose_name='Serviço:')),
                ('descricao', models.TextField(verbose_name='Descrição:')),
                ('icone', models.CharField(default='<i class="bx bx-file">', max_length=300, verbose_name='Ícone:')),
            ],
        ),
        migrations.AlterField(
            model_name='servicospage',
            name='legenda',
            field=models.CharField(blank=True, default='Relação de alguns dos nossos serviços que você aluno(a) pode solicitar online.', max_length=300, null=True, verbose_name='Legenda:'),
        ),
        migrations.AlterField(
            model_name='servicospage',
            name='titulo_two',
            field=models.CharField(default='Serviços', max_length=100, verbose_name='Título II:'),
        ),
    ]
