# Generated by Django 4.0.2 on 2022-03-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0045_servicos_alter_servicospage_legenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestaopage',
            name='imagem',
            field=models.ImageField(upload_to='gestores', verbose_name='Foto:'),
        ),
        migrations.AlterField(
            model_name='gestaopage',
            name='insta',
            field=models.URLField(default='https://www.instagram.com', verbose_name='Instagram:'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='icone',
            field=models.CharField(default='<i class="bx bx-file"></i>', max_length=300, verbose_name='Ícone:'),
        ),
    ]
