# Generated by Django 4.0.2 on 2022-03-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0048_servicos_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_one', models.CharField(default='Saiba mais sobre', max_length=100, verbose_name='Título I:')),
                ('titulo_two', models.CharField(default='nosso colégio', max_length=100, verbose_name='Título II:')),
                ('legenda', models.CharField(blank=True, default='Aqui vamos começar a contar um pouco sobre os nossos 41 anos!', max_length=300, null=True, verbose_name='Legenda:')),
            ],
        ),
        migrations.DeleteModel(
            name='SobrePage',
        ),
    ]
