# Generated by Django 4.0.2 on 2022-03-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0049_sobreheader_delete_sobrepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobrePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título:')),
                ('subtitulo', models.CharField(max_length=300, verbose_name='Subtítulo:')),
                ('texto', models.TextField(verbose_name='Texto:')),
                ('imagem', models.ImageField(default='pages/sobre_defaul.jpg', upload_to='pages', verbose_name='Imagem:')),
            ],
        ),
    ]
