# Generated by Django 4.0.2 on 2022-03-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0051_alter_gestaopage_imagem_alter_sobrepage_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='link',
            field=models.URLField(blank=True, default='', null=True, verbose_name='URL:'),
        ),
    ]
